name: uae_dirham_symbol
description: "Package that can show UAE Dirham symbol with formatted amount in string by applying the amount in double"
version: 0.0.5
homepage: https://github.com/abqamar/uae_dirham_symbol.git
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

   fonts:
     - family: Dirham
       fonts:
         - asset: fonts/dirham_font.ttf